"""Added Category Model

Revision ID: c3d9b9ed5ccd
Revises: 33a55d5034ed
Create Date: 2023-11-05 15:14:07.782636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d9b9ed5ccd'
down_revision: Union[str, None] = '33a55d5034ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('categor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['categor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'categor_id')
    op.drop_table('category')
    # ### end Alembic commands ###
